import { useWeb3React } from '@web3-react/core'
import Spinner from 'components/Spinner/Spinner'
import ApprovalRequest from 'components/Task/ApprovalRequest'
import AssignmentRequest from 'components/Task/AssignmentRequest'
import { ethers } from 'ethers'
import {
  fetchOrganizationCount,
  fetchOrganizations
} from 'hooks/organization/functions'
import {
  assignToSelf,
  fetchTask,
  openTask,
  taskSubmission
} from 'hooks/task/functions'
import { ComplexityScoreMap, Task, TaskStatusMap } from 'hooks/task/types'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { updateCount, updateOrganizations } from 'state/organization/slice'
import { wrapper } from 'state/store'

interface PageProps {
  task: Task
}

export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
  const taskId = context.params?.id?.[0] || '0'
  const task = await fetchTask(parseInt(taskId))
  const orgCount = await fetchOrganizationCount()
  const orgs = await fetchOrganizations(0, orgCount)
  const serializedOrgs = orgs.map((o) => ({
    ...o,
    rewardMultiplier: o.rewardMultiplier.toJSON() ?? null,
    requiredTaskApprovals: o.requiredTaskApprovals.toString(),
    requiredConfirmations: o.requiredConfirmations.toString(),
    rewardToken: o.rewardToken,
    rewardSlashDivisor: o.rewardSlashDivisor.toJSON(),
    slashRewardEvery: o.slashRewardEvery.toString()
  }))

  store.dispatch(updateCount(orgCount))
  store.dispatch(
    updateOrganizations({
      data: serializedOrgs as any,
      page: { from: 0, to: orgCount }
    })
  )

  return {
    props: {
      task: task
    }
  }
})

const TaskPage: NextPage<PageProps> = ({ task }) => {
  const { account, library } = useWeb3React()
  const [rewardToken, setRewardToken] = useState(ethers.constants.AddressZero)
  const [taskComment, setTaskComment] = useState<string>()
  const [processing, setProcessing] = useState(false)
  const [currentTask, setCurrentTask] = useState<Task>(task)
  const taskStatus = Object.entries(TaskStatusMap)[currentTask?.status]?.[1]
  const [errorMsg, setErrorMsg] = useState<string>()

  const getTask = async () => {
    const task = await fetchTask(currentTask?.id, library.getSigner())
    setCurrentTask(task)
  }

  const openCreatedTask = async () => {
    if (!account) {
      setErrorMsg('Connect your wallet')
      return
    }
    setProcessing(true)
    try {
      const tx = await openTask(
        currentTask?.id,
        rewardToken,
        library.getSigner()
      )
      if (tx) {
        await getTask()
      }
      setProcessing(false)
    } catch (e) {
      setProcessing(false)
      console.error('ERROR===', e)
    }
  }

  const assignTaskToSelf = async () => {
    if (!account) {
      setErrorMsg('Connect your wallet')
      return
    }
    try {
      setProcessing(true)
      const tx = await assignToSelf(currentTask?.id, library.getSigner())
      if (tx) {
        await getTask()
      }
      setProcessing(false)
    } catch (e) {
      setProcessing(false)
      console.error('ERROR===', e)
    }
  }

  const submitTask = async () => {
    if (!account) {
      setErrorMsg('Connect your wallet')
      return
    }
    if (!taskComment) {
      setErrorMsg('Add Comment to Submit')
      return
    } else {
      setErrorMsg('')
    }
    setProcessing(true)
    try {
      const tx = await taskSubmission(
        currentTask?.id,
        taskComment,
        library.getSigner()
      )
      if (tx) {
        await getTask()
      }
      setProcessing(false)
    } catch (e) {
      setProcessing(false)
      console.error('ERROR===', e)
    }
  }

  return (
    <div className='container justify-between mx-auto flex flex-wrap p-5 flex-col md:flex-row'>
      <Head>
        <title>Buildstream: Task</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-full h-full top-20 sticky px-5 py-10 bg-white md:basis-4/12 rounded-sm shadow'>
        <h1 className='sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900'>
          {currentTask?.title}
        </h1>
        <p className='lg:w-2/3 leading-relaxed text-base text-gray-500'>
          {currentTask?.description}
        </p>
        <p className='text-lg mt-10 break-all'>
          Organization:{' '}
          <span className='text-sm text-gray-500'>{currentTask?.orgId}</span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Status:{' '}
          <span className='text-sm text-gray-500'>
            {Object.entries(TaskStatusMap)[currentTask?.status]?.[1]}
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Assignee Address:{' '}
          <span className='text-sm text-gray-500'>
            {currentTask?.assigneeAddress.toString()}
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Task Tags:{' '}
          <span className='text-sm text-gray-500'>
            {currentTask?.taskTags.toString()}
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Complexity Score:{' '}
          <span className='text-sm text-gray-500'>
            {
              Object.entries(ComplexityScoreMap)[
                currentTask?.complexityScore
              ]?.[1]
            }
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Reputation Level:{' '}
          <span className='text-sm text-gray-500'>
            {currentTask?.reputationLevel}
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Required approvals:{' '}
          <span className='text-sm text-gray-500'>
            {currentTask?.requiredApprovals}
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Reward amount:{' '}
          <span className='text-sm text-gray-500'>
            {currentTask?.rewardAmount
              ? ethers.utils
                  .formatEther(currentTask?.rewardAmount.toString())
                  .toString()
              : ''}
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Reward token:{' '}
          <span className='text-sm text-gray-500'>
            {currentTask?.rewardToken === ethers.constants.AddressZero
              ? null
              : currentTask?.rewardToken}
          </span>
        </p>
        <p className='text-lg mt-3 break-all'>
          Task Duration:{' '}
          <span className='text-sm text-gray-500'>
            {currentTask?.taskDuration.toString()}
          </span>
        </p>
      </div>
      <div className='w-full h-full md:basis-6/12'>
        <div className='w-full h-full mt-10 bg-gray-100 rounded-lg p-8'>
          <h2 className='text-gray-900 text-lg font-medium title-font mb-5'>
            Task Status
          </h2>
          <div className='mb-3'>
            <p className='text-base text-red-500'>{errorMsg}</p>
          </div>

          <ol className='relative border-l border-gray-200 dark:border-gray-200'>
            <li className='mb-10 ml-4'>
              <div
                className={`absolute w-5 h-5 bg-green-200 mt-1 rounded-full -left-2.5 border border-white ${
                  currentTask?.status > 0 ? 'bg-green-500' : 'bg-gray-900'
                }`}
              ></div>
              <h3
                className={`text-lg font-semibold ${
                  currentTask?.status > 0 ? 'text-green-500' : 'text-gray-900'
                } `}
              >
                Open
              </h3>
              {taskStatus === 'proposed' && (
                <div>
                  <p className='mb-4 text-base font-normal text-gray-500 dark:text-gray-400'>
                    Open task for assignment
                  </p>
                  <input
                    type='text'
                    id='rewardToken'
                    name='rewardToken'
                    value={rewardToken}
                    onChange={(e) => setRewardToken(e.target.value)}
                    data-type='addressArray'
                    placeholder='Reward Token'
                    className='w-full rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                  />
                  <button
                    onClick={openCreatedTask}
                    type='submit'
                    disabled={processing}
                    className='flex text-white bg-indigo-500 border-0 my-2 py-1 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg'
                  >
                    {processing ? <Spinner /> : 'Open Task'}
                  </button>
                </div>
              )}
            </li>
            <li className='mb-10 ml-4'>
              <div
                className={`absolute w-5 h-5 mt-1 rounded-full -left-2.5 border border-white ${
                  currentTask?.status > 1 ? 'bg-green-500' : 'bg-gray-500'
                }`}
              ></div>
              <h3
                className={`text-lg font-semibold ${
                  currentTask?.status > 1 ? 'text-green-500' : 'text-gray-900'
                }`}
              >
                Assign
              </h3>
              {taskStatus === 'open' && (
                <div>
                  <p className='mb-4 text-base font-normal text-gray-500 dark:text-gray-400'>
                    Assign Task
                    <div className='mb-4 text-sm font-normal text-gray-500 dark:text-gray-400'>
                      {currentTask?.reputationLevel <
                        currentTask?.complexityScore &&
                        'You have low reputation level for this task'}
                    </div>
                  </p>
                  <button
                    onClick={assignTaskToSelf}
                    type='submit'
                    disabled={processing}
                    className='flex text-white bg-indigo-500 border-0 my-2 py-1 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg'
                  >
                    {processing ? (
                      <Spinner />
                    ) : currentTask?.reputationLevel >=
                      currentTask?.complexityScore ? (
                      'Assign to self'
                    ) : (
                      'Request Assignment'
                    )}
                  </button>
                </div>
              )}
            </li>
            <li className='mb-10 ml-4'>
              <div
                className={`absolute w-5 h-5 mt-1 rounded-full -left-2.5 border border-white ${
                  currentTask?.status > 2 ? 'bg-green-500' : 'bg-gray-500'
                }`}
              ></div>
              <h3
                className={`text-lg font-semibold ${
                  currentTask?.status > 2 ? 'text-green-500' : 'text-gray-900'
                }`}
              >
                Submit
              </h3>
              {taskStatus === 'assigned' &&
                currentTask?.assigneeAddress === account && (
                  <div>
                    <p className='mb-4 text-base font-normal text-gray-500 dark:text-gray-400'>
                      Ready for submission?
                    </p>
                    <input
                      type='text'
                      id='taskComment'
                      name='taskComment'
                      value={taskComment}
                      onChange={(e) => setTaskComment(e.target.value)}
                      placeholder='Comment'
                      className='w-full rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                    />
                    <button
                      onClick={submitTask}
                      type='submit'
                      disabled={processing}
                      className='flex text-white bg-indigo-500 border-0 my-2 py-1 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg'
                    >
                      {processing ? <Spinner /> : 'Submit'}
                    </button>
                  </div>
                )}
            </li>
            <li className='ml-4'>
              <div
                className={`absolute w-5 h-5 mt-1 rounded-full -left-2.5 border border-white ${
                  currentTask?.status === 4 ? 'bg-green-500' : 'bg-gray-500'
                }`}
              ></div>
              <h3
                className={`text-lg font-semibold ${
                  currentTask?.status === 4 ? 'text-green-500' : 'text-gray-900'
                }`}
              >
                Closed
              </h3>
            </li>
          </ol>
        </div>
        {currentTask.status === 1 && (
          <AssignmentRequest
            taskId={currentTask?.id}
            onAssign={() => getTask()}
          />
        )}
        {currentTask.status === 3 && (
          <ApprovalRequest
            taskId={currentTask?.id}
            orgId={currentTask?.orgId}
            onApprove={() => getTask()}
          />
        )}
      </div>
    </div>
  )
}

export default TaskPage
