import Head from 'next/head'

const CreateTask = () => {
  return (
    <div>
      <Head>
        <title>Buildstream: Create Task</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container w-full mx-auto p-5'>Create Task</div>
    </div>
  )
}

export default CreateTask
