import { ethers } from 'ethers'
import {
  fetchOrganizationCount,
  fetchOrganizationIds
} from 'hooks/organization/functions'
import { fetchTaskCountByOrg, fetchTasksByOrg } from 'hooks/task/functions'
import useTasks from 'hooks/task/useTask'
import type {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage
} from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import { wrapper } from 'state/store'
import { updateCount, updateTasks } from 'state/task/slice'

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps(
    (store) => async (context: GetServerSidePropsContext) => {
      const orgCount = await fetchOrganizationCount()
      const orgIds = await fetchOrganizationIds(0, orgCount)

      const allTasks = await Promise.all(
        orgIds.map(async (orgId) => {
          const taskCount = await fetchTaskCountByOrg(orgId, true, true)
          const tasks = await fetchTasksByOrg(orgId, 0, taskCount)

          return tasks
        })
      )

      const tasks = allTasks.flat()
      store.dispatch(updateCount(tasks.length))
      store.dispatch(
        updateTasks({
          data: tasks,
          page: { from: 0, to: tasks.length }
        })
      )

      return {
        props: {}
      }
    }
  )

const TasksPage: NextPage = () => {
  const { tasks } = useTasks()
  const [selectedTask, setSelectedTask] = useState(0)

  const selected = tasks.find((o) => o.id === selectedTask)

  const onSelect = (id: number) => {
    setSelectedTask(id)
  }
  return (
    <div>
      <Head>
        <title>Buildstream: Tasks</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container w-full mx-auto p-5'>
        <Link href='/task/create'>
          <a className='mr-5 hover:text-gray-900'>
            <button className='bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded'>
              Create
            </button>
          </a>
        </Link>
      </div>
      <div className='container justify-between mx-auto flex flex-wrap p-5 flex-col md:flex-row'>
        <ul className='w-full md:basis-6/12 divide-y divide-gray-100'>
          {tasks.map((task, index) => (
            <li
              key={`${task.id}-${index}`}
              className='p-3 hover:bg-blue-600 hover:text-blue-200'
              onClick={() => onSelect(task.id)}
            >
              <h3 className='font-bold text-xl'>{task.title}</h3>
              <p className='mt-3'>{task.description}</p>
            </li>
          ))}
        </ul>
        <div className='w-full h-full top-20 sticky px-5 py-10 bg-white md:basis-4/12 rounded-sm shadow'>
          <h1 className='sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900'>
            {selected?.title}
          </h1>
          <p className='lg:w-2/3 leading-relaxed text-base text-gray-500'>
            {selected?.description}
          </p>
          <p className='text-lg mt-10 break-all'>
            Organization: <span className='text-sm text-gray-500'>{selected?.orgId}</span>
          </p>
          <p className='text-lg mt-3 break-all'>
            Status: <span className='text-sm text-gray-500'>{selected?.status}</span>
          </p>
          <p className='text-lg mt-10 break-all'>
            Assignee Address:{' '}
            <span className='text-sm text-gray-500'>
              {selected?.assigneeAddress.toString()}
            </span>
          </p>
          <p className='text-lg mt-3 break-all'>
            Task Tags:{' '}
            <span className='text-sm text-gray-500'>
              {selected?.taskTags.map((tag, index) => {
                const seperator: string =
                  index + 1 !== selected.taskTags.length ? ', ' : ''
                return `${tag}${seperator}`
              })}
            </span>
          </p>
          <p className='text-lg mt-3 break-all'>
            Complexity Score:{' '}
            <span className='text-sm text-gray-500'>
              {selected?.complexityScore}
            </span>
          </p>
          <p className='text-lg mt-3 break-all'>
            Reputation Level:{' '}
            <span className='text-sm text-gray-500'>
              {selected?.reputationLevel}
            </span>
          </p>
          <p className='text-lg mt-3 break-all'>
            Required approvals:{' '}
            <span className='text-sm text-gray-500'>
              {selected?.requiredApprovals}
            </span>
          </p>
          <p className='text-lg mt-3 break-all'>
            Reward amount:{' '}
            <span className='text-sm text-gray-500'>
              {selected?.rewardAmount.toString()}
            </span>
          </p>
          <p className='text-lg mt-3 break-all'>
            Reward token:{' '}
            <span className='text-sm text-gray-500'>
              {selected?.rewardToken === ethers.constants.AddressZero
                ? null
                : selected?.rewardToken}
            </span>
          </p>
          <Link href={`/task/${selected?.id}`}>
            <a className='block mt-10 text-blue-700'>{`view ${selected?.title}`}</a>
          </Link>
        </div>
      </div>
    </div>
  )
}

export default TasksPage
