import Head from 'next/head'
import { useRouter } from 'next/router'
import CreateOrgForm from 'components/Organization/CreateOrgForm'

const CreateOrganization: React.FC = () => {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Buildstream: Create Organization</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='text-gray-600 body-font relative'>
        <div className='container px-5 py-24 mx-auto'>
          <div className='flex flex-col w-full mb-12'>
            <h1 className='sm:text-3xl text-center text-2xl font-medium title-font mb-6 text-gray-900'>
              Create Organization
            </h1>
            <CreateOrgForm onCreate={() => router.push(`/v1/organization`)} />
          </div>
        </div>
      </section>
    </div>
  )
}

export default CreateOrganization