import useOrganizations from 'hooks/organization/useOrganization'
import type { NextPage, GetServerSideProps } from 'next'
import { useRouter } from 'next/router'
import {
  getOrganizationCount,
  getOrganizationIds,
  getOrganization
} from 'hooks/organization/functions'
import { Organization } from 'hooks/organization/types'
import { ethers } from 'ethers'
import { useState } from 'react'
import Head from 'next/head'

interface PageProps {
  org: Organization
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const orgId = context.params?.id?.[0] || '0'
  const org = await getOrganization(parseInt(orgId))

  return {
    props: {
      org: {
        ...org,
        rewardMultiplier: org.rewardMultiplier.toNumber()
      }
    }
  }
}

const OrganizationPage: NextPage<PageProps> = ({ org }) => {
  return (
    <div className="container justify-between mx-auto flex flex-wrap p-5 flex-col md:flex-row">
      <Head>
        <title>Buildstream: Organizations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full top-20 sticky px-5 py-10 bg-white md:basis-4/12 rounded-sm shadow">
        <h1 className="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
          {org?.name}
        </h1>
        <p className="lg:w-2/3 leading-relaxed text-base text-gray-500">
          {org?.description}
        </p>
        <p className="text-lg mt-10 break-all">
          Approvers:{' '}
          <span className="text-sm text-gray-500">
            {org?.approvers.toString()}
          </span>
        </p>
        <p className="text-lg mt-3 break-all">
          Reviewers:{' '}
          <span className="text-sm text-gray-500">
            {org?.reviewers.toString()}
          </span>
        </p>
        <p className="text-lg mt-3 break-all">
          Signers:{' '}
          <span className="text-sm text-gray-500">
            {org?.signers.toString()}
          </span>
        </p>
        <p className="text-lg mt-3 break-all">
          Required task approvals:{' '}
          <span className="text-sm text-gray-500">
            {org?.requiredTaskApprovals}
          </span>
        </p>
        <p className="text-lg mt-3 break-all">
          Required confirmations:{' '}
          <span className="text-sm text-gray-500">
            {org?.requiredConfirmations}
          </span>
        </p>
        <p className="text-lg mt-3 break-all">
          Reward multiplier:{' '}
          <span className="text-sm text-gray-500">
            {org?.rewardMultiplier.toString()}
          </span>
        </p>
        <p className="text-lg mt-3 break-all">
          Reward token:{' '}
          <span className="text-sm text-gray-500">
            {org?.rewardToken === ethers.constants.AddressZero
              ? null
              : org?.rewardToken}
          </span>
        </p>
      </div>
    </div>
  )
}

export default OrganizationPage
