import ActionForm from 'components/ActionForm/ActionForm'
import ActionList from 'components/ActionList/ActionList'
import Deposit from 'components/Deposit/Deposit'
import OrgConfigForm from 'components/Organization/OrgConfigForm'
import { BigNumber, ethers } from 'ethers'
import {
  fetchActionCount,
  fetchActions,
  fetchConfirmers
} from 'hooks/action/functions'
import { fetchSingleOrganization } from 'hooks/organization/functions'
import { Organization } from 'hooks/organization/types'
import { fetchTasksByOrg } from 'hooks/task/functions'
import { fetchTreasuryBalances } from 'hooks/treasury/functions'
import useTreasury from 'hooks/treasury/useTreasury'
import type {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage
} from 'next'
import Head from 'next/head'
import {
  updateActions,
  updateConfirmers,
  updateCount as updateActionCount
} from 'state/action/slice'
import { wrapper } from 'state/store'
import { updateCount as updateTaskCount, updateTasks } from 'state/task/slice'
import { updateTreasury } from 'state/treasury/slice'

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps(
    (store) => async (context: GetServerSidePropsContext) => {
      const orgId = parseInt(context.params?.id?.[0] || '0')
      const org = await fetchSingleOrganization(orgId)

      const serializedTreasuryBalances = [
        {
          orgId,
          balances: ((await fetchTreasuryBalances(orgId)) || []).map((b) => ({
            ...b,
            total: b.total.toJSON(),
            locked: b.locked.toJSON()
          }))
        }
      ]
      const tasks = await fetchTasksByOrg()

      const toValue = await fetchActionCount(orgId)
      const fromValue = Math.max(0, toValue - 15)
      const actions = await fetchActions(orgId, fromValue, toValue)

      const confirmers = await Promise.all(
        actions.map(async (action) => {
          const c = await fetchConfirmers(action.id)
          return {
            actionId: action.id,
            confirmers: c
          }
        })
      )

      store.dispatch(updateTaskCount(tasks.length))
      store.dispatch(
        updateTasks({
          data: tasks,
          page: { from: fromValue, to: toValue }
        })
      )
      store.dispatch(updateActionCount(actions.length))
      store.dispatch(
        updateActions({
          data: actions.map((action) => ({
            ...action,
            value: action.value.toString() as any
          })),
          page: { from: 1, to: Math.ceil(actions.length / 10) }
        })
      )
      store.dispatch(updateConfirmers(confirmers))
      store.dispatch(
        updateTreasury({
          data: serializedTreasuryBalances,
          page: { from: 0, to: 1 }
        })
      )

      return {
        props: {
          org: {
            ...org,
            rewardMultiplier: org.rewardMultiplier.toJSON(),
            requiredTaskApprovals: org.requiredTaskApprovals.toString(),
            requiredConfirmations: org.requiredConfirmations.toString(),
            rewardToken: org.rewardToken,
            rewardSlashDivisor: org.rewardSlashDivisor.toJSON(),
            slashRewardEvery: org.slashRewardEvery.toString()
          }
        }
      }
    }
  )

interface PageProps {
  org: Organization
}

const OrganizationPage: NextPage<PageProps> = ({ org }) => {
  const { treasury } = useTreasury()

  return (
    <div className='container mx-auto pb-20'>
      <Head>
        <title>Buildstream: Organizations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {org?.isInitialized ? (
        <div>
          <div className='justify-between flex flex-wrap p-5 flex-col md:flex-row'>
            <div className='w-full h-full py-10 bg-white md:basis-4/12'>
              <h1 className='sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900'>
                {org?.name}
              </h1>
              <p className='lg:w-2/3 leading-relaxed text-base text-gray-500'>
                {org?.description}
              </p>
              <p className='text-lg mt-10 break-all'>
                Approvers:{' '}
                <span className='text-sm text-gray-500'>
                  {org?.approvers.toString()}
                </span>
              </p>
              <p className='text-lg mt-3 break-all'>
                Reviewers:{' '}
                <span className='text-sm text-gray-500'>
                  {org?.reviewers.toString()}
                </span>
              </p>
              <p className='text-lg mt-3 break-all'>
                Signers:{' '}
                <span className='text-sm text-gray-500'>
                  {org?.signers.toString()}
                </span>
              </p>
              <p className='text-lg mt-3 break-all'>
                Required task approvals:{' '}
                <span className='text-sm text-gray-500'>
                  {org?.requiredTaskApprovals
                    ? org?.requiredTaskApprovals.toString()
                    : '0'}
                </span>
              </p>
              <p className='text-lg mt-3 break-all'>
                Required confirmations:{' '}
                <span className='text-sm text-gray-500'>
                  {org?.requiredConfirmations
                    ? org?.requiredConfirmations.toString()
                    : '0'}
                </span>
              </p>
              <p className='text-lg mt-3 break-all'>
                Balance:{' '}
                {treasury
                  ?.find((t) => t.orgId === org.id)
                  ?.balances?.map((b, index) => (
                    <span key={index} className='text-sm text-gray-500'>
                      {ethers.utils.formatUnits(
                        BigNumber.from(b.total)?.toString(),
                        b.tokenInfo?.decimal
                      )}
                    </span>
                  ))}
              </p>
              <p className='text-lg mt-3 break-all'>
                Reward multiplier:{' '}
                <span className='text-sm text-gray-500'>
                  {org?.rewardMultiplier
                    ? ethers.utils
                        .formatEther(
                          BigNumber.from(org?.rewardMultiplier).toString()
                        )
                        .toString()
                    : ''}
                </span>
              </p>
              <p className='text-lg mt-3 break-all'>
                Reward token:{' '}
                <span className='text-sm text-gray-500'>
                  {org?.rewardToken === ethers.constants.AddressZero
                    ? null
                    : org?.rewardToken}
                </span>
              </p>
            </div>
            <div className='w-full h-full mt-10 md:basis-6/12 bg-gray-100 rounded-lg p-8'>
              <Deposit org={org} />
            </div>
          </div>
          <div className='justify-between flex flex-wrap p-5 flex-col md:flex-row'>
            <div className='w-full h-full mt-10 md:basis-5/12'>
              <ActionList orgId={org.id} />
            </div>
            <div className='w-full h-full mt-10 md:basis-6/12 bg-gray-100 rounded-lg p-8'>
              <ActionForm org={org} />
            </div>
          </div>
        </div>
      ) : (
        <div className='justify-between flex flex-wrap p-5 flex-col md:flex-row'>
          <div className='w-full h-full py-10 bg-white'>
            <h1 className='sm:text-3xl text-center text-2xl font-medium title-font mb-6 text-gray-900'>
              Complete Organization Data
            </h1>
            <OrgConfigForm orgId={org?.id} />
          </div>
        </div>
      )}
    </div>
  )
}

export default OrganizationPage
