import Head from 'next/head'
import CreateOrganizationForm from 'components/Organization/Create/CreateOrganizationForm'

const CreateOrganization: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Buildstream: Create Organization</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container grid-layout py-24'>
        <div className='col-span-5'>
          <h1 className='text-8xl mb-8 font-bold'>Start as Organization</h1>
          <p className='w-3/5 text-lg text-secondary'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dolor,
            lobortis auctor amet, sit amet. Nisl parturient nisl.
          </p>
        </div>

        <div className='paper col-span-7 py-12 rounded-[46px] relative'>
          <CreateOrganizationForm />
        </div>
      </div>
    </div>
  )
}

export default CreateOrganization
