import Head from 'next/head'
import CreateOrganizationForm from 'components/Organization/Create/CreateOrganizationForm'
import { GetServerSideProps, GetServerSidePropsContext } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'react-i18next'
import { wrapper } from 'state/store'

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps(
    (store) => async (context: GetServerSidePropsContext) => {
      const locale = context.locale ?? ''

      return {
        props: {
          ...(await serverSideTranslations(locale, [
            'common',
            'organization',
            'header'
          ]))
        }
      }
    }
  )

const CreateOrganization: React.FC = () => {
  const { t } = useTranslation('organization')
  return (
    <div>
      <Head>
        <title>Buildstream: Create Organization</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='layout-container grid-layout py-24'>
        <div className='col-span-4 md:col-span-8 lg:col-span-5'>
          <h1 className='text-5xl lg:text-8xl mb-8 font-bold'>
            {t('start_as_org')}
          </h1>
          <p className='lg:w-3/5 text-lg text-secondary'>
            {t('start_as_org_sub')}
          </p>
        </div>

        <div className='paper col-span-4 md:col-span-8 lg:col-start-7 px-10 py-12 rounded-[46px] relative'>
          <CreateOrganizationForm />
        </div>
      </div>
    </div>
  )
}

export default CreateOrganization
