import React, { useState, useRef } from 'react'
import type { GetServerSideProps, NextPage } from 'next'
import { wrapper } from 'state/store'
import { editTask } from 'hooks/task/functions'
import { Task } from 'hooks/task/types'
import Head from 'next/head'
import { ComplexityScoreMap } from 'hooks/task/types'
import { useWeb3React } from '@web3-react/core'
import { useRouter } from 'next/router'
import client from 'graphclient/client'
import { GetTaskDocument } from 'graphclient'
import { TaskDurationCalc } from 'utils/task_duration'

interface PageProps {
  task: Task
}

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (context) => {
    const taskId = context.params?.id?.[0] || '0'
    const { data } = await client.query({
      query: GetTaskDocument,
      variables: {
        id: taskId
      }
    })

    return {
      props: {
        task: data.task
      }
    }
  })

const EditTask: React.FC<PageProps> = ({ task }) => {
  const [taskData, setTaskData] = useState({
    ...task,
    weeks: TaskDurationCalc.getDurationSegments(task.taskDuration).weeks,
    days: TaskDurationCalc.getDurationSegments(task.taskDuration).days,
    hours: TaskDurationCalc.getDurationSegments(task.taskDuration).hours
  })
  const [errorMsg, setErrorMsg] = useState<string>()
  const [status, setStatus] = useState({ text: '', error: false })
  const taskComplexities = Object.entries(ComplexityScoreMap)
  const [processing, setProcessing] = useState(false)
  const { account, library } = useWeb3React()
  const router = useRouter()
  const tagRef = useRef<any>('')
  const weeksSelection = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  const daysSelection = [0, 1, 2, 3, 4, 5, 6]
  const hoursSelection = [0, 1, 2, 4, 8, 16]

  const handleChange = (ev: any) => {
    const targetName = ev.target.name
    let targetValue: string | number = ev.target.value

    if (ev.target.type === 'number' || targetName === 'orgId') {
      if (targetValue) {
        targetValue = Number(targetValue)
      }
    }

    if (ev.target.name === 'taskTags') {
      if (ev.key === 'Enter') {
        setTaskData((prev: any) => ({
          ...prev,
          [targetName]: [...prev.taskTags, targetValue]
        }))
        tagRef.current.value = ''
      }
      return
    }
    setTaskData((prev) => ({ ...prev, [targetName]: targetValue }))
  }

  const deleteTag = (ev: any) => {
    const index = parseInt(ev.target.id)

    let tagUpdate = [...taskData.taskTags]
    tagUpdate.splice(index, 1)

    setTaskData((prev) => ({ ...prev, taskTags: [...tagUpdate] }))
  }

  const editCurrentTask = async () => {
    if (!account) {
      setStatus({ text: 'Wallet Not Connected', error: true })
      return
    }
    const taskDuration = TaskDurationCalc.getDurationInSeconds({
      weeks: taskData.weeks,
      days: taskData.days,
      hours: taskData.hours
    })
    if (taskDuration === 0) {
      setStatus({ text: 'Wrong Task Duration Input', error: true })
      return
    }
    setProcessing(true)
    try {
      const response = await editTask(
        taskData.id,
        taskData.title,
        taskData.description,
        taskData.taskTags,
        taskData.complexityScore,
        taskData.reputationLevel,
        taskDuration,
        library.getSigner()
      )
      setProcessing(false)
      if (response) router.push(`/task`)
    } catch (e) {
      setProcessing(false)
      console.error(e)
    }
  }

  return (
    <div>
      <Head>
        <title>Buildstream: Edit Task</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='text-gray-600 body-font relative'>
        <div className='container px-5 py-24 mx-auto'>
          <div className='flex flex-col text-center w-full mb-12'>
            <h1 className='sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900'>
              Edit Task
            </h1>
            <p
              className={`lg:w-2/3 mx-auto leading-relaxed text-base ${
                status.error ? 'text-red-500' : 'text-green-500'
              }`}
            >
              {status.text}
            </p>
          </div>
          <div className='lg:w-1/2 md:w-2/3 mx-auto'>
            <div className='flex flex-wrap -m-2'>
              <div className='p-2 w-full'>
                <div className='relative'>
                  <label
                    htmlFor='title'
                    className='leading-7 text-sm text-gray-600'
                  >
                    Task Title
                  </label>
                  <input
                    type='text'
                    id='title'
                    name='title'
                    value={taskData.title}
                    onChange={handleChange}
                    className='w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                  />
                </div>
              </div>
              <div className='p-2 w-full'>
                <div className='relative'>
                  <label
                    htmlFor='complexityScore'
                    className='leading-7 text-sm text-gray-600'
                  >
                    Complexity Score
                  </label>
                  <select
                    id='complexityScore'
                    value={taskData?.complexityScore}
                    onChange={handleChange}
                    name='complexityScore'
                    className='w-full bg-gray-100 py-3 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                  >
                    {taskComplexities.map(([key, value]) => {
                      return (
                        <option key={key} value={key}>
                          {value.toLocaleUpperCase()}
                        </option>
                      )
                    })}
                  </select>
                </div>
              </div>
              <div className='p-2 w-full'>
                <div className='relative'>
                  <label
                    htmlFor='reputationLevel'
                    className='leading-7 text-sm text-gray-600'
                  >
                    Reputational Level
                  </label>
                  <input
                    type='number'
                    id='reputationLevel'
                    name='reputationLevel'
                    value={taskData.reputationLevel}
                    onChange={handleChange}
                    className='w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                  />
                </div>
              </div>
              <div className='p-2 w-full'>
                <div className='relative'>
                  <div className='flex justify-between gap-x-2'>
                    <div className='w-full'>
                      <label
                        htmlFor='taskDuration'
                        className='leading-7 text-sm text-gray-600 block'
                      >
                        Duration(Weeks)
                      </label>
                      <select
                        id='weeks'
                        name='weeks'
                        value={taskData.weeks}
                        onChange={handleChange}
                        className='w-full bg-gray-100 py-3 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                      >
                        {weeksSelection.map((value) => {
                          return (
                            <option key={value} value={value}>
                              {value}
                            </option>
                          )
                        })}
                      </select>
                    </div>

                    <div className='w-full'>
                      <label
                        htmlFor='taskDuration'
                        className='leading-7 text-sm text-gray-600 block'
                      >
                        Days
                      </label>
                      <select
                        id='days'
                        name='days'
                        value={taskData.days}
                        onChange={handleChange}
                        className='w-full bg-gray-100 py-3 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                      >
                        {daysSelection.map((value) => {
                          return (
                            <option key={value} value={value}>
                              {value}
                            </option>
                          )
                        })}
                      </select>
                    </div>

                    <div className='w-full'>
                      <label
                        htmlFor='taskDuration'
                        className='leading-7 text-sm text-gray-600 block'
                      >
                        Hours
                      </label>
                      <select
                        id='hours'
                        name='hours'
                        value={taskData.hours}
                        onChange={handleChange}
                        className='w-full bg-gray-100 py-3 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                      >
                        {hoursSelection.map((value) => {
                          return (
                            <option key={value} value={value}>
                              {value}
                            </option>
                          )
                        })}
                      </select>
                    </div>
                  </div>
                </div>
              </div>
              <div className='p-2 w-full'>
                <div className='relative'>
                  <label
                    htmlFor='reputationLevel'
                    className='leading-7 text-sm text-gray-600'
                  >
                    Task Tags
                  </label>
                  <input
                    type='text'
                    id='taskTags'
                    name='taskTags'
                    ref={tagRef}
                    onKeyDown={handleChange}
                    placeholder='Type and Press Enter Key'
                    className='w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out'
                  />
                </div>
                <div className='mt-3 h-auto flex flex-wrap item-center gap-x-2 gap-y-2'>
                  {taskData.taskTags.length > 0 &&
                    taskData.taskTags.map((task, index) => {
                      return (
                        <div
                          key={task}
                          className='flex items-center border-2 rounded-full px-2 py-1 w-max'
                        >
                          {task}
                          <div
                            onClick={deleteTag}
                            id={`${index}`}
                            className='py-1 px-3 ml-3 rounded-full bg-indigo-400 text-red-50 hover:bg-indigo-500 cursor-pointer'
                          >
                            x
                          </div>
                        </div>
                      )
                    })}
                </div>
              </div>
              <div className='p-2 w-full'>
                <div className='relative'>
                  <label
                    htmlFor='description'
                    className='leading-7 text-sm text-gray-600'
                  >
                    Description
                  </label>
                  <textarea
                    id='description'
                    name='description'
                    value={taskData.description}
                    onChange={handleChange}
                    className='w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out'
                  ></textarea>
                </div>
              </div>
              <div className='p-2 w-full'>
                <button
                  type='button'
                  onClick={editCurrentTask}
                  className='flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg'
                >
                  {processing ? 'Processing...' : 'Edit'}
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default EditTask
